### With this request we get all the movies
GET http://localhost:1234/movies

### Get a movie by its id using params in the request
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Get movies filtering by genre
GET http://localhost:1234/movies?genre=romance
###
GET http://localhost:1234/movies?director=nolan
###
GET http://localhost:1234/movies?title=The+Godfather

### POST a new movie
POST http://localhost:1234/movies
content-type: application/json

{
    "title": "Enojadamente Velozes",
	"year": 1934,
  	"director": "Francis Ford Coppola",
  	"duration": 175,
  	"poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  	"genre": [
  	  "Crime",
  	  "Drama"
  	] ,
	"views": 12322200
}

### Do a PATCH to change the year of a resource

PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
	"year": 2000
}

### DELETE a movie
DELETE http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
